name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test-build-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps
        run: |
          pip install -r order-api/requirements.txt
          pip install pytest httpx

      - name: Run tests
        run: pytest -q
        working-directory: order-api

      - name: Build Docker image
        run: docker build -t order-api:ci ./order-api

      - name: Trivy scan (informational for now)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'order-api:ci'
          format: 'table'
          vuln-type: 'os,library'
          exit-code: '0'   # do not fail yet; we’ll flip to 1 after Azure setup
